name: Performance Test JMeter

on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
      - 'feature/*'

jobs:

  performance_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout

      # Example: Replace with a linter script that you can include directly in your repository
      - name: Lint all YAML files in the directory
        run: |
          # Insert your linting commands/scripts here

      # Example: Replace with your JMeter test execution steps (if you have scripts in your repository)
      - name: Run JMeter Test
        run: |
          # Insert your JMeter test execution commands/scripts here

      # Example: Replace with commands to upload test results (if applicable and scripts are in your repository)
      - name: Upload JMeter Test Results
        run: |
          # Insert commands to upload test results here

  image_scan:
    needs: performance_test
    runs-on: ubuntu-latest

    steps:
      # Example: Replace with your Docker build and scan commands (if scripts are in your repository)
      - name: Build Apache JMeter Image
        run: |
          # Insert commands to build Docker image here

      # Example: Replace with commands to scan Docker image (if scripts are in your repository)
      - name: Scan Apache JMeter Image
        run: |
          # Insert commands to scan Docker image here

      # Example: Replace with commands to upload scan results (if applicable and scripts are in your repository)
      - name: Upload Anchore scan SARIF report
        run: |
          # Insert commands to upload scan results here

      # Example: Replace with inspection commands (if applicable and scripts are in your repository)
      - name: Inspect action SARIF report
        run: |
          # Insert commands to inspect scan results here
