name: Run JMeter Test

on:
  push:
    branches:
      - main  # Adjust branch name as per your default branch

jobs:
  performance_test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
    
    - name: Run JMeter Test
      run: |
        mkdir -p results
        jmeter -n -t POC-PerformanceTesting-Jmeter/tests/Jmeter.jmx -l results/results.jtl
    
    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: results/results.jtl
